const mongoose = require('mongoose');
const Product = require('../models/Product');

const MONGO_URI = 'mongodb+srv://zhanat_db_user:oDaCJQeuD2mjTpGp@m0.fkbeejx.mongodb.net/matkasym';

const onoiSaktaProducts = [
  {
    name: 'Паллетные стеллажи',
    fullName: 'Паллетные стеллажи ONOI SAKTA',
    sku: 'OS-PALLET',
    brand: 'matkasym-shaar',
    set: 'onoi-sakta',
    category: 'Складское оборудование',
    price: 0,
    priceUndefined: true,
    description: 'Профессиональные стеллажи для хранения паллетированных грузов. Каждая паллета — отдельная ячейка с прямым доступом. Конструкция из стоек и балок, простая и надёжная.',
    images: ['https://onoi-sakta.onrender.com/images/image5.jpeg'],
    isSupplied: true,
    supplier: { company: 'JIUWEI', sku: 'JW-PALLET' },
    stock: 0,
    productStatus: 'for_sale',
  },
  {
    name: 'Полочные стеллажи',
    fullName: 'Полочные стеллажи ONOI SAKTA',
    sku: 'OS-SHELF',
    brand: 'matkasym-shaar',
    set: 'onoi-sakta',
    category: 'Складское оборудование',
    price: 0,
    priceUndefined: true,
    description: 'Универсальные стеллажи для ручного размещения штучных товаров. Сборная конструкция с регулируемыми полками. Доступны лёгкие (150 кг), средние (300 кг) и тяжёлые (500 кг) варианты.',
    images: ['https://onoi-sakta.onrender.com/images/image102.jpeg'],
    isSupplied: true,
    supplier: { company: 'JIUWEI', sku: 'JW-SHELF' },
    stock: 0,
    productStatus: 'for_sale',
  },
  {
    name: 'Узкопроходные стеллажи (VNA)',
    fullName: 'Узкопроходные стеллажи (VNA) ONOI SAKTA',
    sku: 'OS-VNA',
    brand: 'matkasym-shaar',
    set: 'onoi-sakta',
    category: 'Складское оборудование',
    price: 0,
    priceUndefined: true,
    description: 'Высокоплотное хранение с узкими проходами 1.5-2 м (вместо стандартных 3-5 м). Погрузчики движутся по направляющим рельсам — высокая безопасность и точность.',
    images: ['https://onoi-sakta.onrender.com/images/image85.jpeg'],
    isSupplied: true,
    supplier: { company: 'JIUWEI', sku: 'JW-VNA' },
    stock: 0,
    productStatus: 'for_sale',
  },
  {
    name: 'Двухглубинные стеллажи',
    fullName: 'Двухглубинные стеллажи ONOI SAKTA',
    sku: 'OS-DOUBLE',
    brand: 'matkasym-shaar',
    set: 'onoi-sakta',
    category: 'Складское оборудование',
    price: 0,
    priceUndefined: true,
    description: 'Развитие паллетных стеллажей с двойной глубиной — удваивают ёмкость хранения. Средняя оборачиваемость запасов, 50% селективность.',
    images: ['https://onoi-sakta.onrender.com/images/image116.jpeg'],
    isSupplied: true,
    supplier: { company: 'JIUWEI', sku: 'JW-DOUBLE' },
    stock: 0,
    productStatus: 'for_sale',
  },
  {
    name: 'Шаттловые стеллажи',
    fullName: 'Шаттловые стеллажи ONOI SAKTA',
    sku: 'OS-SHUTTLE',
    brand: 'matkasym-shaar',
    set: 'onoi-sakta',
    category: 'Складское оборудование',
    price: 0,
    priceUndefined: true,
    description: 'Высокоплотная система хранения с автоматическими шаттлами. Шаттлы перемещают паллеты внутри каналов — минимум ручных операций.',
    images: ['https://onoi-sakta.onrender.com/images/image112.jpeg'],
    isSupplied: true,
    supplier: { company: 'JIUWEI', sku: 'JW-SHUTTLE' },
    stock: 0,
    productStatus: 'for_sale',
  },
  {
    name: 'Консольные стеллажи',
    fullName: 'Консольные стеллажи ONOI SAKTA',
    sku: 'OS-CANTILEVER',
    brand: 'matkasym-shaar',
    set: 'onoi-sakta',
    category: 'Складское оборудование',
    price: 0,
    priceUndefined: true,
    description: 'Специализированные стеллажи для длинномерных грузов: труб, профиля, досок, рулонов. Консоли крепятся к вертикальным стойкам.',
    images: ['https://onoi-sakta.onrender.com/images/image95.jpeg'],
    isSupplied: true,
    supplier: { company: 'JIUWEI', sku: 'JW-CANTILEVER' },
    stock: 0,
    productStatus: 'for_sale',
  },
  {
    name: 'Проходные стеллажи (Drive-in)',
    fullName: 'Проходные стеллажи (Drive-in) ONOI SAKTA',
    sku: 'OS-DRIVEIN',
    brand: 'matkasym-shaar',
    set: 'onoi-sakta',
    category: 'Складское оборудование',
    price: 0,
    priceUndefined: true,
    description: 'Стеллажи с въездом погрузчика внутрь конструкции. Максимальная плотность хранения однотипных грузов большими партиями.',
    images: ['https://onoi-sakta.onrender.com/images/image120.jpeg'],
    isSupplied: true,
    supplier: { company: 'JIUWEI', sku: 'JW-DRIVEIN' },
    stock: 0,
    productStatus: 'for_sale',
  },
  {
    name: 'Гравитационные стеллажи',
    fullName: 'Гравитационные стеллажи ONOI SAKTA',
    sku: 'OS-FLOW',
    brand: 'matkasym-shaar',
    set: 'onoi-sakta',
    category: 'Складское оборудование',
    price: 0,
    priceUndefined: true,
    description: 'Стеллажи с роликовыми дорожками под наклоном. Грузы движутся под действием гравитации — автоматический FIFO.',
    images: ['https://onoi-sakta.onrender.com/images/image104.jpeg'],
    isSupplied: true,
    supplier: { company: 'JIUWEI', sku: 'JW-FLOW' },
    stock: 0,
    productStatus: 'for_sale',
  },
  {
    name: 'Многоярусные стеллажи (мезонин)',
    fullName: 'Многоярусные стеллажи (мезонин) ONOI SAKTA',
    sku: 'OS-MEZZANINE',
    brand: 'matkasym-shaar',
    set: 'onoi-sakta',
    category: 'Складское оборудование',
    price: 0,
    priceUndefined: true,
    description: 'Создание дополнительных ярусов над существующими стеллажами. 2-3 уровня для хранения лёгких и средних грузов.',
    images: ['https://onoi-sakta.onrender.com/images/image93.jpeg'],
    isSupplied: true,
    supplier: { company: 'JIUWEI', sku: 'JW-MEZZANINE' },
    stock: 0,
    productStatus: 'for_sale',
  },
  {
    name: 'Стальные платформы',
    fullName: 'Стальные платформы ONOI SAKTA',
    sku: 'OS-PLATFORM',
    brand: 'matkasym-shaar',
    set: 'onoi-sakta',
    category: 'Складское оборудование',
    price: 0,
    priceUndefined: true,
    description: 'Увеличение полезной площади склада в 2-3 раза за счёт создания дополнительных этажей. Подъём грузов: гидроплатформы, подъёмники, конвейеры.',
    images: ['https://onoi-sakta.onrender.com/images/image66.jpeg'],
    isSupplied: true,
    supplier: { company: 'JIUWEI', sku: 'JW-PLATFORM' },
    stock: 0,
    productStatus: 'for_sale',
  },
  {
    name: 'Стеллажи для пресс-форм',
    fullName: 'Стеллажи для пресс-форм ONOI SAKTA',
    sku: 'OS-MOLD',
    brand: 'matkasym-shaar',
    set: 'onoi-sakta',
    category: 'Складское оборудование',
    price: 0,
    priceUndefined: true,
    description: 'Специализированные тяжёлые стеллажи для хранения пресс-форм и штампов. Выдвижные ящики с высокой нагрузкой.',
    images: ['https://onoi-sakta.onrender.com/images/image115.jpeg'],
    isSupplied: true,
    supplier: { company: 'JIUWEI', sku: 'JW-MOLD' },
    stock: 0,
    productStatus: 'for_sale',
  },
  {
    name: 'Автоматизированные склады (AS/RS)',
    fullName: 'Автоматизированные склады (AS/RS) ONOI SAKTA',
    sku: 'OS-ASRS',
    brand: 'matkasym-shaar',
    set: 'onoi-sakta',
    category: 'Автоматизация',
    price: 0,
    priceUndefined: true,
    description: 'Высокотехнологичная система хранения с автоматическими штабелёрами. Высота 5-40 м, интеграция с WMS. Полностью автоматический приём и выдача грузов.',
    images: ['https://onoi-sakta.onrender.com/images/image50.jpeg'],
    isSupplied: true,
    supplier: { company: 'JIUWEI', sku: 'JW-ASRS' },
    stock: 0,
    productStatus: 'for_sale',
  },
  {
    name: 'Шаттловая складская система',
    fullName: 'Шаттловая складская система ONOI SAKTA',
    sku: 'OS-SHUTTLE-SYS',
    brand: 'matkasym-shaar',
    set: 'onoi-sakta',
    category: 'Автоматизация',
    price: 0,
    priceUndefined: true,
    description: '4-сторонние шаттлы с автоматическими подъёмниками и конвейерами. Сочетание высокой плотности хранения с автоматизацией.',
    images: ['https://onoi-sakta.onrender.com/images/image112.jpeg'],
    isSupplied: true,
    supplier: { company: 'JIUWEI', sku: 'JW-SHUTTLE-SYS' },
    stock: 0,
    productStatus: 'for_sale',
  },
  {
    name: 'Лёгкий полочный стеллаж',
    fullName: 'Лёгкий полочный стеллаж ONOI SAKTA',
    sku: 'OS-LIGHT-SHELF',
    brand: 'matkasym-shaar',
    set: 'onoi-sakta',
    category: 'Складское оборудование',
    price: 0,
    priceUndefined: true,
    description: 'Лёгкие полочные стеллажи для хранения небольших грузов. Идеально для архивов, офисов и магазинов.',
    images: ['https://onoi-sakta.onrender.com/images/image102.jpeg'],
    isSupplied: true,
    supplier: { company: 'JIUWEI', sku: 'JW-LIGHT-SHELF' },
    stock: 0,
    productStatus: 'for_sale',
  },
  {
    name: 'Средний полочный стеллаж',
    fullName: 'Средний полочный стеллаж ONOI SAKTA',
    sku: 'OS-MEDIUM-SHELF',
    brand: 'matkasym-shaar',
    set: 'onoi-sakta',
    category: 'Складское оборудование',
    price: 0,
    priceUndefined: true,
    description: 'Полочные стеллажи средней нагрузки для складов и производств. Усиленная конструкция с балками и полками повышенной прочности.',
    images: ['https://onoi-sakta.onrender.com/images/image107.jpeg'],
    isSupplied: true,
    supplier: { company: 'JIUWEI', sku: 'JW-MEDIUM-SHELF' },
    stock: 0,
    productStatus: 'for_sale',
  },
];

async function addProducts() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('Connected to MongoDB');

    for (const product of onoiSaktaProducts) {
      const existing = await Product.findOne({ sku: product.sku });
      if (existing) {
        console.log(`Skipping ${product.sku} - already exists`);
        continue;
      }

      const newProduct = new Product(product);
      await newProduct.save();
      console.log(`Added: ${product.name}`);
    }

    console.log('Done!');
    process.exit(0);
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

addProducts();
